"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";

type Game = { matchId: string; startedAt: string; home: string; away: string; homeGoals: number; awayGoals: number; homeShootout: number; awayShootout: number; specialEnd: boolean };
type Series = { id: string; label: string; bestOf: number; participants: string[]; games: Game[]; score: Record<string, number>; complete: boolean; winner: string | null; advancingLoser: string | null; note?: string };
type LiveData = { connected: boolean; reason?: string; updatedAt: string; startsAt: string; status: "scheduled" | "live" | "complete"; rounds: { opening: Series[]; semifinal: Series[]; final: Series }; matchedGames: number; mojiri: string | null };

const kickoff = new Date("2026-08-21T21:30:00+09:00");
const clock = (value: string) => new Intl.DateTimeFormat("ko-KR", { hour: "2-digit", minute: "2-digit", hour12: false }).format(new Date(`${value}+09:00`));

function SeriesCard({ series, final = false }: { series: Series; final?: boolean }) {
  const needed = Math.ceil(series.bestOf / 2);
  return <article className={`live-series ${series.complete ? "complete" : ""} ${final ? "final" : ""}`}><header><span>{series.label}</span><b>{series.bestOf ? `${series.bestOf}판 ${needed}선승` : "부전패"}</b></header><div className="live-versus">{series.participants.length ? series.participants.map((name) => <div className={series.advancingLoser === name ? "advancing" : series.winner === name ? "escaped" : ""} key={name}><span>{name.slice(0,1)}</span><strong>{name}<small>{series.advancingLoser === name ? final ? "★ 이달의 모지리" : "패자 진출" : series.winner === name ? "승리 탈출" : "경기 대기"}</small></strong><b>{series.score[name] ?? 0}</b></div>) : <p>이전 라운드 결과 대기 중</p>}</div>{series.note && <p className="live-note">{series.note}</p>}{series.games.length > 0 && <div className="live-games">{series.games.map((game, index) => <Link href={`/matches/${game.matchId}`} key={game.matchId}><time>{clock(game.startedAt)}</time><span>G{index + 1}</span><strong>{game.home}</strong><b>{game.homeGoals} : {game.awayGoals}</b><strong>{game.away}</strong><i>›</i></Link>)}</div>}</article>;
}

export function MojiriLiveClient() {
  const [data, setData] = useState<LiveData | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [now, setNow] = useState(0);
  const refresh = useCallback(async () => { setLoading(true); try { const response = await fetch("/api/mojiri/live", { cache: "no-store" }); const value = await response.json(); if (!response.ok || !value.connected) throw new Error(value.reason || "라이브 기록을 불러오지 못했습니다."); setData(value); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "라이브 기록을 불러오지 못했습니다."); } finally { setLoading(false); } }, []);
  useEffect(() => { setNow(Date.now()); refresh(); const poll = window.setInterval(refresh, 45000); const timer = window.setInterval(() => setNow(Date.now()), 1000); return () => { clearInterval(poll); clearInterval(timer); }; }, [refresh]);
  const countdown = useMemo(() => { const seconds = Math.max(0, Math.floor((kickoff.getTime() - now) / 1000)); return { hours: Math.floor(seconds / 3600), minutes: Math.floor(seconds % 3600 / 60), seconds: seconds % 60 }; }, [now]);
  const allGames = data ? [...data.rounds.opening, ...data.rounds.semifinal, data.rounds.final].flatMap((series) => series.games.map((game) => ({ ...game, series: series.label }))).sort((a,b) => a.startedAt.localeCompare(b.startedAt)) : [];
  return <section className="live-shell"><div className="live-toolbar"><div><i className={data?.status === "live" ? "on" : ""}/><span>{data?.status === "complete" ? "대회 종료" : data?.status === "live" ? "LIVE 집계 중" : now ? `시작까지 ${countdown.hours}시간 ${countdown.minutes}분 ${countdown.seconds}초` : "시작 시간 계산 중"}</span><small>{data ? `매칭 ${data.matchedGames}경기 · ${new Date(data.updatedAt).toLocaleTimeString("ko-KR")} 확인` : "경기 기록 연결 중"}</small></div><button type="button" onClick={refresh} disabled={loading}>{loading ? "확인 중…" : "지금 새로고침"}</button></div>{error && <p className="live-error">{error}</p>}{data ? <><div className="live-bracket"><section><header><span>ROUND 01</span><h2>1라운드</h2></header><div>{data.rounds.opening.map((series) => <SeriesCard series={series} key={series.id}/>)}</div></section><section><header><span>ROUND 02</span><h2>패자 준결승</h2></header><div>{data.rounds.semifinal.map((series) => <SeriesCard series={series} key={series.id}/>)}</div></section><section><header><span>FINAL</span><h2>모지리 결정전</h2></header><div><SeriesCard series={data.rounds.final} final/></div></section></div>{data.mojiri && <aside className="live-mojiri"><span>2026 AUGUST · NEW MOJIRI</span><strong>🤡 {data.mojiri}</strong></aside>}<section className="live-timeline"><header><div><span>AUTO MATCH LOG</span><h2>자동 인식 경기</h2></div><p>21:30 이후 · 대진 참가자 조합 기준</p></header>{allGames.length ? <div>{allGames.map((game) => <Link href={`/matches/${game.matchId}`} key={game.matchId}><time>{clock(game.startedAt)}</time><span>{game.series}</span><strong>{game.home}</strong><b>{game.homeGoals} : {game.awayGoals}</b><strong>{game.away}</strong><i>상세 ›</i></Link>)}</div> : <p className="live-empty">아직 인식된 경기가 없습니다. 경기 종료 후 NEXON 기록 등록까지 잠시 걸릴 수 있습니다.</p>}</section></> : <div className="live-loading">대진표와 최신 경기 기록을 준비하는 중…</div>}<aside className="live-caution"><b>자동 집계 기준</b><span>오늘 21:30 이후 확정 대진 참가자끼리 진행한 리그 친선경기를 시간순으로 연결합니다. 각 시리즈는 한쪽이 목표 승수에 도달하면 종료되며 이후 같은 조합의 경기는 포함하지 않습니다.</span></aside></section>;
}
